name: Automated Accessibility Tests

on:
  pull_request:
  workflow_dispatch:
  # Optional: Add schedule if you want these tests to run on a regular basis
  # schedule:
  #   - cron: '0 2 * * 1-5' # Runs at 2 AM UTC Monday-Friday

jobs:
  automated-a11y:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.18.0]
        api-version: ["v71"] # Using only latest API version for a11y tests
        runner-browser: ["chromium"] # Often a11y tests only need to run on one browser
    env:
      CHECKOUT_API_KEY: ${{secrets.ADYEN_CHECKOUT_API_KEY}}
      MERCHANT_ACCOUNT: ${{secrets.ADYEN_CHECKOUT_MERCHANT_ACCOUNT}}
      CLIENT_KEY: ${{secrets.ADYEN_CHECKOUT_CLIENT_KEY}}
      CLIENT_ENV: test
      TESTING_ENVIRONMENT: https://checkout-test.adyen.com/checkout/${{matrix.api-version}}
      API_VERSION: ${{matrix.api-version}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      id: node-modules-cache
      uses: actions/cache@v4
      env:
        cache-name: node-modules-v1
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Enable Corepack
      run: corepack enable

    - name: Install Project Dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable

    - name: Extract Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies["@playwright/test"]' packages/e2e-playwright/package.json)" >> $GITHUB_ENV

    - name: Cache Playwright
      # Using a cache for the webkit binary files causes this error on subsequent runs
      # /home/runner/.cache/ms-playwright/webkit-2123/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory
      if: matrix.runner-browser != 'webkit'
      id: playwright-cache
      uses: actions/cache@v4
      env:
        cache-name: playwright-v1
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-node-${{ matrix.node-version }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-browser-${{ matrix.runner-browser }}

    - name: Install Playwright Dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true' || matrix.runner-browser == 'webkit'
      run: npx playwright install --with-deps ${{ matrix.runner-browser }}

    - name: Run Automated Accessibility Tests
      run: yarn test:automated-a11y --project=${{ matrix.runner-browser }}
    
    - name: Archive test result artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: a11y-report-${{matrix.api-version}}-${{matrix.runner-browser}}-${{ github.sha }}
        path: packages/e2e-playwright/playwright-report
        retention-days: 5
