## If the latest commit message contains '[ci] release main', trigger release-build.yml
name: Check Commit Message

on:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      trigger_release: ${{ steps.check_commit_message.outputs.trigger_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get commit message
        id: get_commit_message
        run: echo "message=$(git log -1 --format=%s)" >> $GITHUB_OUTPUT

      - name: Check commit message
        id: check_commit_message
        run: |
          if [[ "${{ steps.get_commit_message.outputs.message }}" == *"[ci] release main"* ]]; then
            echo "Commit message contains '[ci] release main', triggering release build..."
            echo "trigger_release=true" >> $GITHUB_OUTPUT
          else
            echo "Commit message does not contain '[ci] release main', skipping release build..."
            exit 0
          fi

  trigger-release-build:
    needs: check-commit-message
    if: needs.check-commit-message.outputs.trigger_release == 'true'
    uses: ./.github/workflows/release-build.yml
