name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Install Project Dependencies
        run: yarn install --immutable

      # Copy README to adyen-web package
      - run: cp README.md packages/lib/

      # Copy LICENSE to adyen-web package
      - run: cp LICENSE packages/lib/

      # Build and publish to npm
      - name: Build and release
        run: cd packages/lib && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true
