# This workflow will run tests using node and then publish a package when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build UMD and Translations

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-umd-and-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Install Project Dependencies
        run: yarn install
      # Build
      - name: Build
        run: cd packages/lib && npm run build
        env:
          CI: true

      # Upload UMD and translations
      - run: cp packages/server/translations/ packages/lib/dist/umd -r
      - uses: actions/upload-artifact@v6
        with:
          name: adyen-web-poc-6.31.0-poc_cdn
          path: packages/lib/dist/umd
