name: Update Visual Test Screenshots

on:
  pull_request:
    types: [labeled]

jobs:
  update-screenshots:
    if: github.event.label.name == 'screenshot'
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      CHECKOUT_API_KEY: ${{secrets.ADYEN_CHECKOUT_API_KEY}}
      MERCHANT_ACCOUNT: ${{secrets.ADYEN_CHECKOUT_MERCHANT_ACCOUNT}}
      CLIENT_KEY: ${{secrets.ADYEN_CHECKOUT_CLIENT_KEY}}
      CLIENT_ENV: test
      TESTING_ENVIRONMENT: https://checkout-test.adyen.com/checkout/v71
      API_VERSION: v71
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 22.18.0
        package-manager-cache: false

    - name: Cache node modules
      id: node-modules-cache
      uses: actions/cache@v4
      env:
        cache-name: node-modules-v1
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-node-22.18.0-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Enable Corepack
      run: corepack enable

    - name: Install Project Dependencies
      run: yarn install --immutable


    - name: Install Playwright Dependencies
      run: npx playwright install --with-deps

    - name: Update automated visual tests screenshots
      run: yarn test:automated-visual:update-screenshots

    - name: Update e2e test screenshots
      run: yarn test:e2e:update-screenshots

    - name: Commit updated screenshots
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add packages/e2e-playwright/tests/
        if ! git diff --staged --quiet; then
          git commit -m "chore: update screenshots"
          git push
        else
          echo "No screenshot changes to commit"
        fi

    - name: Archive test result artifacts
      id: upload-artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: playwright-report-update-screenshots-${{ github.sha }}
        path: packages/e2e-playwright/playwright-report
        retention-days: 5

    - name: Remove screenshot label
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            name: 'screenshot'
          });

